### ISSUE TITLE
TrasactionStateFailed

### ISSUE THREAD

**Issue by AmeinEskinder** [lucdotdev/hover_ussd#4]
**TrasactionStateFailed**

Hey brother thanks for this cool plugin it helps a lot, lately I was reading this package and I could not wait to test it but today I had the chance to look at it, it was very simple compared to documentation that I've red but later on after creating my api and hooking up together and onTapped my first _ussd.sendUssd I got transaction state failed but later on when I went to the useHover dashboard every thing was getting logged there perfectly I looked at my terminal there was no any strange thing that was taking place but my eyes spotted a negative sentence <unregisterNetworkCallback; CallingUid : 10197, CallingPid : 25376>, can you give me a hand on this????

![image](https://user-images.githubusercontent.com/62555273/137817122-fae6f5e7-8c6b-4306-b080-7beb2989ada2.png)

**Comment by muhammed-amein** [comment]
and when I kept trying again and again it is giving this random error 
<Timeout triggered
E/HoverRequest(25376): setting request error: ERROR 3001: Timeout reached, please check your USSD network connection and your action configurations.
I/TransactionSequence(25376): Finished carrying out action, cleaning up.
E/HoverActivity(25376): Failure: null>

**Comment by muhammed-amein** [comment]
And now when I have changed the release version of useHover to the latest 1.7.2 it is working but it is working in debug mode where I can see the sdk dialing the Ussd and navigating through the menus is there a way that we can make it run in the background

**Comment by lucdotdev** [comment]
thanks for submitting your issue, look like some trouble through hover android sdk, does it work also in release mode with 1.7.2 hover sdk version ?

**Comment by muhammed-amein** [comment]
when upgrading the SDKversion to 1.7.2 it works fine but only in debug mode,
and I think that is due to the deprecations and changes to the SDK

**Comment by lucdotdev** [comment]
is the latest version of the package do you use ? v 1.0.0?

**Comment by muhammed-amein** [comment]
Yes

**Comment by muhammed-amein** [comment]
am using these packages

  get: ^4.3.8
  reorderableitemsview: ^2.0.1
  widget_loading: ^0.2.1
  hive: ^2.0.4
  hive_flutter: 
  animations: ^2.0.1
  flutter_markdown: ^0.6.6
  smart_dropdown: ^1.0.0
  flutter_bounceable: ^1.0.0
  hover_ussd: ^1.0.0
  uuid: ^3.0.5
  path_provider: ^2.0.4
  advance_notification: ^1.0.5
  pretty_qr_code: ^2.0.2
  qr_code_scanner: ^0.5.2

**Comment by muhammed-amein** [comment]
Btw I have observed that in one of your branchs you were using the latest SDK 1.7.2 and in the main branch you are using this version in the gradle "implementation 'com.hover:android-sdk:1.6.3'"

**Comment by lucdotdev** [comment]
okay im gonna to check that, i' m working rigth now on v2.0.0 and planning to put at pub.dev today ;
i will update the hover sdk that version and looking at you if the issue persist

**Comment by muhammed-amein** [comment]
while using Hover's runner app they made tree approach for performing USSD calls debug mode, normal mode and offline approach for simulating with out sim card so it is good if you can made those methods available in the 2.0 version

**Comment by muhammed-amein** [comment]
Helloo there brother @lucdotdev any progress yet?

**Comment by lucdotdev** [comment]
Currently in wip, you can check and test it at
https://github.com/lucdotdev/hover_ussd/tree/v2.0.0

```yaml

hover_ussd:
    git:
      url: git@github.com:lucdotdev/hover_ussd.git
      ref: v2.0.0
```

**Comment by muhammed-amein** [comment]
Hey @lucdotdev I have seen the new version and it looks great, alots of improvement.
you did a great job but is there is a way that we can customize the result page?

**Comment by muhammed-amein** [comment]
Hey again @lucdotdev have you seen this log before 

when using this commad in _hoverUssd.sendUssd(actionId: "ea8583ef");
the app is crashing. 

Request valid, confirming any variables or PIN with user.
D/AndroidRuntime(16999): Shutting down VM
E/AndroidRuntime(16999): FATAL EXCEPTION: main
E/AndroidRuntime(16999): Process: com.goosh.pays, PID: 16999
E/AndroidRuntime(16999): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=0, data=null} to activity {com.goosh.pays/com.goosh.pays.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.EventChannel$EventSink.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(16999):        at android.app.ActivityThread.deliverResults(ActivityThread.java:5511)
E/AndroidRuntime(16999):        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5552)
E/AndroidRuntime(16999):        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(16999):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(16999):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(16999):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
E/AndroidRuntime(16999):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(16999):        at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime(16999):        at android.app.ActivityThread.main(ActivityThread.java:8528)
E/AndroidRuntime(16999):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16999):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(16999):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/AndroidRuntime(16999): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.EventChannel$EventSink.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(16999):        at com.lucdotdev.hover_ussd.HoverUssdPlugin.onActivityResult(HoverUssdPlugin.java:150)
E/AndroidRuntime(16999):        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:741)
E/AndroidRuntime(16999):        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:426)
E/AndroidRuntime(16999):        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:749)
E/AndroidRuntime(16999):        at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:651)
E/AndroidRuntime(16999):        at android.app.Activity.dispatchActivityResult(Activity.java:8550)
E/AndroidRuntime(16999):        at android.app.ActivityThread.deliverResults(ActivityThread.java:5504)
E/AndroidRuntime(16999):        ... 11 more
I/Process (16999): Sending signal.

**Comment by lucdotdev** [comment]
yes you can do that with passing your logo and branding in **HoverUssd.initialize();**

**Comment by muhammed-amein** [comment]
Even though am not good with react have you passed on the arguments for the extra's?

**Comment by G33kfleek** [comment]
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: '../../third_party/dart/runtime/vm/object.cc: 4484: error: Unable to use class Library:'package:hover_ussd/hover_ussd.dart' Class: HoverUssd which is not loaded yet.'
package:hover_ussd/hover_ussd.dart:1
    r0  00000000  r1  00005b3a  r2  00000006  r3  7cc3c140
    r4  7cc3c154  r5  7cc3c138  r6  00005a73  r7  0000016b
    r8  7cc3c150  r9  7cc3c140  r10 7cc3c170  r11 7cc3c160
    ip  00005b3a  sp  7cc3c110  lr  a781ecb7  pc  a781ecca
backtrace:
      #00 pc 0005ecca  /apex/com.android.runtime/lib/bionic/libc.so (abort+166) (BuildId: 3fa995c8295bf39cdb0dfd6a7c02dad2)
      #01 pc 015df5bf  /data/app/com.example.flutter_application-ltZXm4PmAXIyHgZEzpEQyg==/base.apk!libflutter.so (offset 0x6d78000) (BuildId: 68f943e46d7bdceab2b8b5bdc5e55c67c89941aa)
Crash thread undumpable
Lost connection to device.

**Comment by G33kfleek** [comment]
> Even though am not good with react have you passed on the arguments for the extra's?

yeah but it keeps  crashing.

**Comment by muhammed-amein** [comment]
Are you using the SDK or a plugin from pub.dev?

**Comment by G33kfleek** [comment]
> Are you using the SDK or a plugin from pub.dev?

am using the version 2 branch (SDK which I installed locally and pointed the path to it pubspec.yml 
![image](https://user-images.githubusercontent.com/104208543/173666634-2e2b5226-a65e-4fd6-8f54-f8eac0efd2f1.png)

**Comment by muhammed-amein** [comment]
Instead, have you tried fetching from Pub.dev?

**Comment by G33kfleek** [comment]
> Instead, have you tried fetching from Pub.dev?

even the one from package from pubdev brings the same error

**Comment by muhammed-amein** [comment]
Next, do this
1: Increase your target SDK and in the build Gradle.
2: Execute flutter clean.
3: If it persists it will be a problem from Hover SDK version first check these.
